# SPDX-FileCopyrightText: 2024 Matthew Mark Ibbetson
# SPDX-FileContributor: Matthew Mark Ibbetson
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Rust CI

on:
  pull_request:

jobs:
  correctness-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust stable toolchain
        run: |
          rustup update stable
          rustup default stable
          rustup component add rustfmt clippy

      - name: Run cargo fmt
        run: cargo fmt -- --check

      - name: Run cargo check
        run: cargo check

      - name: Run cargo clippy
        run: cargo clippy

      - name: Run cargo test
        run: cargo test --verbose

  reuse-compliance-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v5
